include:
  - local: '.gitlab/ci/prebuild.yml'
  - remote: https://gitlab.com/ynezz/openwrt-ci/raw/master/openwrt-ci/gitlab/main.yml

stages:
  - pre-build
  - test

check HTML, CSS and SVG with html5validator:
  stage: pre-build
  image: cyb3rjak3/html5validator:latest
  script:
    - html5validator --root www --also-check-css --also-check-svg --show-warnings --log INFO
